### ISSUE TITLE
[FEATURE REQ.] An option to make boats only step up on land

### ISSUE THREAD

**Issue by Drigonis** [btwonion/better-boat-movement#4]
Trying to reproduce a change in a recent snapshot which was subsequently removed (can't remember which one) which allowed you to step up blocks when in boats. Would also be neat if you could make the boat's step-up height be boosted when on ice. I think it'd be a little jarring if you could just row up any old hill, but the implications for ice boating is great. Also because it just gets a little irritating when you're traveling through a windy river and keep stepping up onto land.

**Comment by btwonion** [comment]
hi,
i will add this option in the coming version. Thanks for the suggestion.

**Comment by btwonion** [comment]
implemented with version 2.1.0 and commit 465032a
