### ISSUE TITLE
Stepping up slabs doesn't work

### ISSUE THREAD

**Issue by Disketaa** [btwonion/better-boat-movement#8]
I can step-up grass paths, snow layers, but when I'm adjusting boat's step-up height, nothing changes

**Comment by btwonion** [comment]
Hi,
thanks for reporting this. I will look into it.

**Comment by btwonion** [comment]
What version of bbm are you using?
I could not recreate this behaviour, but if you're using 2.2.4, make sure to disable boostOnIce, when also using boostOnBlocks.
Please give me feedback on this.

**Comment by btwonion** [comment]
Hi,
due to the lack of response and because I couldn't recreate the error, I will close this error for now. If you still experience this error, feel free to reopen this issue later.
